site_name: Edu-Wiki
site_description: 高中知识维基百科
site_author: Edu-Wiki Team
site_url: https://edu-wiki.pages.dev/
repo_name: Nick-zheng-official/edu-wiki
repo_url: https://github.com/Nick-zheng-official/edu-wiki
edit_uri: blob/master/docs/docs/
copyright: Copyright &copy; 2025 Edu-Wiki Team
use_directory_urls: true

theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  favicon: static/img/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - 语文:
      - 语文简介: chinese/introduction.md
  - 数学:
      - 数学简介: math/introduction.md
      - 导数:
          - 端点效应: math/calculus/endpoint-effect.md
          - 极值点偏移: math/calculus/extreme-point-offset.md
      - 数学技巧: math/math-tricks.md
      - 原神:
          - 启动: math/genshin/start.md
  - 英语:
      - 英语简介: english/introduction.md
  - 物理:
      - 物理简介: physics/introduction.md
      - 运动学:
          - 冲量与动量: physics/kinematics/impulse-and-momentum.md
      - 磁学:
          - 电磁感应: physics/magnetism/electromagnetic-induction.md
  - 化学:
      - 化学简介: chemistry/introduction.md
      - 化学反应原理:
          - 化学反应速率: chemistry/chemical-reaction-principles/chemical-reaction-rate.md
  - 生物:
      - 生物简介: biology/introduction.md
      - 生物与环境:
          - 生态系统: biology/environment/ecosystem.md

markdown_extensions:
  # 基础扩展
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - abbr

  # 数学公式扩展
  - pymdownx.arithmatex

  # PyMdown Extensions
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ""
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ""
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  copyright: 本作品采用 知识共享署名-非商业性使用 4.0 国际许可协议 (CC BY-NC 4.0) 进行许可

extra_javascript:
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - static/js/extra.js
  - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - static/css/extra.css
