site_name: Edu-Wiki
site_description: 高中知识维基百科
site_author: Edu-Wiki Team
site_url: https://edu-wiki.pages.dev/
repo_name: Nick-zheng-official/edu-wiki
repo_url: https://github.com/Nick-zheng-official/edu-wiki
edit_uri: blob/master/docs/docs/
copyright: Copyright &copy; 2025 Edu-Wiki Team
use_directory_urls: true

theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  icon:
    repo: fontawesome/brands/github-alt
  logo: static/img/logo.png
  favicon: static/img/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
  font:
    text: Noto Sans
    code: Source Code Pro

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - 首页: index.md
  - 测试文档: test.md
  - LaTeX 测试: latex-test.md
  - 换行测试: test-break.md
  - 语文:
      - 简介: chinese/index.md
  - 数学:
      - 简介: math/index.md
  - 英语:
      - 简介: english/index.md
  - 物理:
      - 简介: physics/index.md
      - 冲量与动量: physics/impulse-and-momentum.md
  - 化学:
      - 简介: chemistry/index.md
  - 生物:
      - 简介: biology/index.md

markdown_extensions:
  # 基础扩展
  - admonition
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - attr_list
  - abbr
  
  # 数学公式扩展
  - pymdownx.arithmatex
  
  # PyMdown Extensions
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ""
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ""
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  copyright: CC BY-NC-SA 4.0

extra_javascript:
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - static/js/extra.js
  - https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - static/css/extra.css